### ISSUE TITLE
Lua support

### ISSUE THREAD

**Issue by mathstuf** [sardemff7/eventd-bindings#1]
So I started looking into this. Some interesting differences from Python (all values are stored on the stack and lgi has no C API, so there's some "call Lua code from C" hoops to jump through).

**Comment by sardemff7** [comment]
I started to work on this (and Perl and JS), will push as soon as it builds.

**Comment by sardemff7** [comment]
Pushed 2f7d9911fcb72e55470bab2ee2d6e369eea01178 as a base.

The only remaining _big_ thing is to tell Lua `key_file` and `event` are `GObject`s.
My attempt user `lua_setmetatable` is not as successful as I hoped…

**Comment by mathstuf** [comment]
You can [call](https://github.com/pavouk/lgi/issues/69#issuecomment-36002767) either of these:

``` lua
GLib.Keyfile(key_file)
lgi.core.record.new(GLib.Keyfile, key_file)
```

to make an `lgi` object from a pointer. The first is preferred, but it seems some types do some wonky magic (`GLib.Bytes` based on that comment).

**Comment by sardemff7** [comment]
That’s better, see 4413315a37d66134265fce65310e0b291ab2609f.
It does not work, but at least it runs!
